spring:
  datasource:
    url: jdbc:mysql://teampool-db.cfsye4sy4bwo.ap-northeast-2.rds.amazonaws.com:3306/teampool_db?useSSL=false&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: loopmaet123!!

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: update

logging:
  level:
    org.hibernate.SQL: debug